Feature/ecbuild35
JCSDA-internal/FMS pull request #24
Opened 2021-03-21 18:48 UTC by mmiesch

**Description**

This is part of a series of PRs for a description see:

https://github.com/JCSDA-internal/fv3-bundle/pull/50

This introduces minor updates for compatibility with ecbuild 3.5.0

partially fixes: https://github.com/JCSDA-internal/jedi-stack/issues/19

**How Has This Been Tested?**

This has been incorporated into JEDI fv3-bundle and all tests have passed

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2021-03-22 14:12 UTC, danholdaway approved these changes

2021-03-29 15:09 UTC, ytremolet approved these changes

2021-04-06 16:50 UTC, markjolah requested changes
See the documentation for [jedicmake/FindNetCDF](https://github.com/JCSDA-internal/jedi-cmake/blob/develop/cmake/Modules/FindNetCDF.cmake).  This should explain how to properly use the Module.  There is no need to use `include_directories()`.  The jedicmake NetCDF targets already export all the paths and libraries you need.  All that is needed to `target_link_libraries(<tgt> PUBLIC NetCDF::NetCDF_<LANG>)`.  This is what is happening when you set the `PUBLIC_LIBS NetCDF::NetCDF_<LANG>` argument to `ecbuild_add_library()`.

2021-04-06 16:50 UTC, markjolah commented on CMakeLists.txt
> +set( NETCDF_F90 ON CACHE BOOL "Compile with Fortran NetCDF" )
This variable is not used by jedi cmake FindNetCDF.

2021-04-06 16:50 UTC, markjolah commented on CMakeLists.txt
> +include_directories( ${NetCDF_INCLUDE_DIRS} )
`include_directories()` is not necessary for NetCDF targets.

2021-04-06 16:50 UTC, markjolah commented on CMakeLists.txt
> +                     PUBLIC_LIBS     ${NetCDF_LIBRARIES}
This should be `PUBLIC_LIBS NetCDF::NetCDF_Fortran`

2021-04-06 16:50 UTC, markjolah commented on CMakeLists.txt
> +                     PUBLIC_INCLUDES ${NetCDF_INCLUDE_DIRS}
This is not necessary.  The NetCDF targets are already exporting their include directories.

2021-04-06 16:54 UTC, markjolah commented on CMakeLists.txt
> +   install(DIRECTORY ${CMAKE_Fortran_MODULE_DIRECTORY}/${CMAKE_CFG_INTDIR} DESTINATION ${INSTALL_INCLUDE_DIR} )
Change `INSTALL_INCLUDE_DIR` -> `CMAKE_INSTALL_INCLUDEDIR`.

2021-04-06 16:54 UTC, markjolah commented on CMakeLists.txt
> +                    $<INSTALL_INTERFACE:${INSTALL_INCLUDE_DIR}> )
Change `INSTALL_INCLUDE_DIR` -> `CMAKE_INSTALL_INCLUDEDIR`.

2021-04-06 17:37 UTC, mmiesch commented
@markjolah - when I make your requested changes, the build fails with this:

```
[ 34%] Linking Fortran shared library ../lib/libfms.dylib
Undefined symbols for architecture x86_64:
  "___netcdf_MOD_nf90_close", referenced from:
      ___netcdf_io_mod_MOD_netcdf_file_close in netcdf_io.F90.o
  "___netcdf_MOD_nf90_copy_att", referenced from:
      ___blackboxio_MOD_copy_metadata in blackboxio.F90.o
  "___netcdf_MOD_nf90_create", referenced from:
      ___blackboxio_MOD_create_diskless_netcdf_file in blackboxio.F90.o
      ___netcdf_io_mod_MOD_netcdf_file_open in netcdf_io.F90.o
  "___netcdf_MOD_nf90_def_dim", referenced from:
      ___blackboxio_MOD_copy_metadata in blackboxio.F90.o
      ___netcdf_io_mod_MOD_netcdf_add_dimension in netcdf_io.F90.o
  "___netcdf_MOD_nf90_def_var_manydims", referenced from:
      ___blackboxio_MOD_copy_metadata in blackboxio.F90.o
      ___netcdf_io_mod_MOD_netcdf_add_variable in netcdf_io.F90.o
  "___netcdf_MOD_nf90_def_var_scalar", referenced from:
      ___netcdf_io_mod_MOD_netcdf_add_variable in netcdf_io.F90.o
  "___netcdf_MOD_nf90_enddef", referenced from:
      ___netcdf_io_mod_MOD_set_netcdf_mode in netcdf_io.F90.o
  "___netcdf_MOD_nf90_get_att_eightbyteint", referenced from:
      ___netcdf_io_mod_MOD_get_variable_attribute_1d in netcdf_io.F90.o
      ___netcdf_io_mod_MOD_get_global_attribute_1d in netcdf_io.F90.o
  "___netcdf_MOD_nf90_get_att_eightbytereal", referenced from:
      ___netcdf_io_mod_MOD_get_variable_attribute_1d in netcdf_io.F90.o

[...]
```

2021-04-06 18:28 UTC, mmiesch commented on CMakeLists.txt
> +                     PUBLIC_LIBS     ${NetCDF_LIBRARIES}
It looks like this is the culprit.  If I make this change, the build fails.  The other changes seem to work.

2021-04-07 15:47 UTC, markjolah commented
@mmiesch You need to build with `VERBOSE=1` to see the actual compilation lines.  It looks like you are not correctly getting the FindNetCDF from `jedicmake`, and perhaps still using that provided from `ecbuild`.

2021-04-07 15:57 UTC, mmiesch commented
Thanks @markjolah but I don't want to spend too much time debugging this - I've got other things to debug with test failures and containers.  The point of these PRs was just to get things working, and they work.  We can refine & clean up the cmake later.

2021-04-07 21:48 UTC, markjolah approved these changes

2021-05-11 18:21 UTC, merged